# Generated by Django 4.2.5 on 2023-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.CharField(max_length=10000)),
                ('PId', models.CharField(max_length=10000)),
                ('PName', models.CharField(max_length=10000)),
                ('City', models.CharField(max_length=10000)),
                ('Hospital_Name', models.CharField(max_length=10000)),
                ('Gender', models.CharField(max_length=10000)),
                ('BMI', models.CharField(max_length=10000)),
                ('DOB', models.CharField(max_length=10000)),
                ('Hieght', models.CharField(max_length=10000)),
                ('Weight', models.CharField(max_length=10000)),
                ('Diabetic', models.CharField(max_length=10000)),
            ],
        ),
    ]
