# Generated by Django 4.2.5 on 2023-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprofilez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='BMI',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='City',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='DOB',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Diabetic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Hieght',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Hospital_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='PId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='PName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='S_No',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Weight',
            field=models.CharField(max_length=255),
        ),
    ]
